### ISSUE TITLE
Sonar does not pick up NUnit Tests

### ISSUE THREAD

**Issue by TheLastColonial** [TheLastColonial/SeedWork#1]
Currently Sonar is seeing the code smells of a project but not the code coverage.
I believe this is because the report is either not being generated or being passed correctly to Sonar.

**Comment by TheLastColonial** [comment]
https://github.com/coverlet-coverage/coverlet#Quick-Start
https://medium.com/purplebricks-digital/getting-code-coverage-showing-in-sonar-cloud-99a2295407b3

**Comment by TheLastColonial** [comment]
Need to produce report via coverlet and in the OpenCover format.

Install into Test project:
``` XML
<ItemGroup>
    <PackageReference Include="coverlet.msbuild" Version="3.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="OpenCover" Version="4.7.922" />
  </ItemGroup>
```

This then needs declaring in the YAML
``` YAML
- name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        shell: powershell
        run: |
          .\.sonar\scanner\dotnet-sonarscanner begin /k:"TheLastColonial_SeedWork" /o:"thelastcolonial" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths=".\**\coverage.opencover.xml"
          dotnet build --no-restore
          dotnet test --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
          .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
```
